# Generated by Django 2.1.1 on 2018-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0004_auto_20181106_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(help_text='Optional. 30 characters or fewer.', max_length=30, null=True, verbose_name='display_name'),
        ),
    ]
