# Generated by Django 2.1.1 on 2018-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0005_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
