# Generated by Django 2.1.1 on 2018-11-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0007_auto_20181106_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
