# Generated by Django 2.1.1 on 2018-11-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0009_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.FloatField(default=0)),
                ('exercises', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='dateTime of the workout')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
