# Generated by Django 2.1.1 on 2018-11-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0010_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='waist',
        ),
    ]
